name: favorites
description: "Favorites App — COMP 6970 Assignment 3 — Jahidul Arafat"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/amsterdam.jpeg
    - assets/images/capetown.jpeg
    - assets/images/copenhagen.jpeg
    - assets/images/lisbon.jpeg
    - assets/images/london.jpeg
    - assets/images/losangeles.jpeg
    - assets/images/monaco.jpeg
    - assets/images/reykjavik.jpeg
    - assets/images/warsaw.jpeg
    - assets/images/app_logo.png
